# intended for Docker Stack which does NOT build image. "docker compose up"-able btw
version: '3'

services:
    alpine:
        image: hanshazairi/42ools
        working_dir: /sources/
        volumes:
            - .:/vol
        command:
            - /bin/sh
            - -c
            - |
                echo 'export CFLAGS="-Wall -Wextra -Werror -std=c89 -pedantic"' >> /root/.bashrc
                echo 'if [ -f Makefile ]; then printf "\033[33mAuto-executing `pwd`/Makefile... Ctrl+C to cancel\033[0m\n"; make; fi' >> /root/.bashrc
                apk add git && git clone https://github.com/Koh42/get_next_line.git ./
                sleep infinity

    # ubuntu:
    #     image: ubuntu
    #     command:
    #         - /bin/sh
    #         - -c
    #         - |
    #             apt-get update
    #             apt-get install -y python3-pip
    #             pip3 install --no-cache-dir norminette
    #             apt-get install -y git build-essential clang valgrind
    #             sleep infinity

    # portainer:
    #     image: portainer/portainer-ce:latest
    #     ports:
    #         - '9000:9000'
    #     volumes:
    #         - /var/run/docker.sock:/var/run/docker.sock

    console:
        image: bitbull/docker-exec-web-console
        depends_on:
            - alpine
        ports:
            - '8888:8888'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            CONTEXT_PATH: /
            INDEX_HTML: |
                <!DOCTYPE html>
                <html>
                <head>
                    <title>Terminal</title>
                    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/xterm@5.3.0/css/xterm.min.css" />
                    <script src="https://cdn.jsdelivr.net/npm/xterm@5.3.0/lib/xterm.js" integrity="sha256-8K6g919IVZATrmZDwked1zfSbaQtVSTm0rcJFa5lI8c=" crossorigin="anonymous"></script>
                    <script src="https://cdn.jsdelivr.net/npm/xterm-addon-attach@0.9.0/lib/xterm-addon-attach.js" integrity="sha256-uK3FNCsUNFSUuRK4Pw+CNfGxSj9i8f/Ht/XBnstI2Os=" crossorigin="anonymous"></script>
                    <script src="https://cdn.jsdelivr.net/npm/xterm-addon-fit@0.8.0/lib/xterm-addon-fit.js" integrity="sha256-EPMZTF8XwXhvt9XbhlweyFObZzajGAY/04var3xGhI8=" crossorigin="anonymous"></script>
                    <script>
                        window.onload = function() {
                            const term = new window.Terminal();
                            term.open(document.getElementById('terminal'));
                            window.term = term;

                            const containerId = 'CONTAINER_ID_PLACEHOLDER';
                            const url  =  ("ws://"
                                + window.location.hostname + ":" + window.location.port
                                + window.location.pathname + "exec/"
                                + containerId + ',' + window.btoa('/bin/bash'));
                            const socket = new WebSocket(url);
                            const attachAddon = new AttachAddon.AttachAddon(socket);
                            term.loadAddon(attachAddon);

                            const fitAddon = new FitAddon.FitAddon();
                            term.loadAddon(fitAddon);
                            fitAddon.fit();
                            window.addEventListener('resize', function(event){
                                fitAddon.fit();
                            });
                        };
                    </script>
                </head>
                <body style="background-color: #000; overflow: hidden; height: 100vh;">
                <div id="terminal" style="width: 100%; height: 100%;"></div>
                </body>
                </html>
        entrypoint:
            - /bin/sh
            - -c
            - |
                socat TCP-LISTEN:2735,reuseaddr,fork UNIX-CONNECT:/var/run/docker.sock &

                # workaround old-version busybox wget/telnet issue
                printf 'GET /containers/json?filters={"ancestor":["hanshazairi/42ools"]} HTTP/1.1\r\nHost: localhost\r\n\r\n' > /tmp/req
                while [ -z "$$CID" ]
                do
                    timeout -t 1 tail -f /tmp/req | socat UNIX-CONNECT:/var/run/docker.sock - > /tmp/res
                    CID=`grep '"Id":' /tmp/res | cut  -b 9-17`
                done
                echo "$$INDEX_HTML" | sed "s/CONTAINER_ID_PLACEHOLDER/$$CID/" > /index.html

                /main